- name: "修改core-site配置文件"
  template: src=core-site.j2 dest=/data/hadoop/etc/hadoop/core-site.xml
- name: "修改hdfs-site配置文件"
  template: src=hdfs-site.j2 dest=/data/hadoop/etc/hadoop/hdfs-site.xml
- name: "修改yarn-site配置文件"
  template: src=yarn-site.j2 dest=/data/hadoop/etc/hadoop/yarn-site.xml
- name: "修改mapred-site配置文件"
  template: src=mapred-site.j2 dest=/data/hadoop/etc/hadoop/mapred-site.xml
- name: "修改mapred-site配置文件"
  copy: src=capacity-scheduler.xml dest=/data/hadoop/etc/hadoop/capacity-scheduler.xml
- name: "修改hadoop-env配置文件"
  copy: src=hadoop-env.sh dest=/data/hadoop/etc/hadoop/hadoop-env.sh
- name: "生成格式化namenode脚本"
  template: src=format-namenode.j2 dest=/tmp/format-namenode.sh mode=744

