
- name: "覆盖hive-site配置文件"
  template: src=hive-site.j2 dest=/data/hive/conf/hive-site.xml
- name: "新增spark-defaults配置文件"
  copy: src=spark-defaults.conf dest=/data/hive/conf/spark-defaults.conf
- name: "覆盖hive-env配置文件"
  copy: src=hive-env.sh dest=/data/hive/conf/hive-env.sh



