- name: "修改配置文件"
  template: src=azkaban_properties.j2 dest=/data/azkaban_server/conf/azkaban.properties
- name: "修改默认密码"
  copy: src=azkaban-users.xml dest=/data/azkaban_server/conf/azkaban-users.xml mode=744
- name: "生成启动脚本"
  copy: src=start-azkaban-server.sh dest=/tmp/start-azkaban-server.sh mode=744
