---
# 解决某些脚本文件无法兼容wins换行符 初始化变量文件 指定azkaban、hive元数据 数据库(mysql) 的账号密码
- hosts: master
  remote_user: root
  roles:
    - role: master
      vars:
        init_db_port: 3306
        init_db_username: root
        init_db_password: Abc1234%
